# train all baselines
python data/ensemble_quadruped/train_ensemble_dynamics_quadruped.py
python run_experiment.py --mode train --experiment_name quadruped_model_based --wandb_project blackbox_deepreach --wandb_entity zeyuanfe --wandb_name quadruped_model_based --wandb_group QuadrupedBaselines  --dynamics_class Quadruped --minWith target --tMax 0.6  --pretrain --pretrain_iters 1000 --num_epochs 82000 --counter_end 80000 --num_nl 512 --lr 6e-6 --deepReach_model exact --method model_based --set_mode avoid --collisionR 0.5 --val_time_resolution 6 --ham_estimator_fname None
python run_experiment.py --mode train --experiment_name quadruped_Ham-CA --wandb_project blackbox_deepreach --wandb_entity zeyuanfe --wandb_name quadruped_Ham-CA --wandb_group QuadrupedBaselines  --dynamics_class Quadruped --minWith target --tMax 0.6  --pretrain --pretrain_iters 1000 --num_epochs 82000 --counter_end 80000 --num_nl 512 --lr 6e-6 --deepReach_model exact --method 1AM3 --set_mode avoid --collisionR 0.5 --val_time_resolution 6 --ham_estimator_fname None
python run_experiment.py --mode train --experiment_name quadruped_FVI --wandb_project blackbox_deepreach --wandb_entity zeyuanfe --wandb_name quadruped_FVI --wandb_group QuadrupedBaselines  --dynamics_class Quadruped --minWith target --tMax 0.6  --pretrain --pretrain_iters 1000 --num_epochs 82000 --counter_end 80000 --num_nl 512 --lr 6e-6 --deepReach_model exact --method 1AM1 --set_mode avoid --collisionR 0.5 --val_time_resolution 6 --ham_estimator_fname None
python run_experiment.py --mode train --experiment_name quadruped_D-FVI --wandb_project blackbox_deepreach --wandb_entity zeyuanfe --wandb_name quadruped_D-FVI --wandb_group QuadrupedBaselines  --dynamics_class Quadruped --minWith target --tMax 0.6  --pretrain --pretrain_iters 1000 --num_epochs 82000 --counter_end 80000 --num_nl 512 --lr 6e-6 --deepReach_model exact --method 1AM2 --set_mode avoid --collisionR 0.5 --val_time_resolution 6 --ham_estimator_fname None
# test all baselines
python run_experiment.py --mode test --experiment_name quadruped_model_based --dt 0.02 --checkpoint_toload -1 --num_scenarios 1000000 --num_violations 10000 --control_type value --data_step run_robust_recovery --wandb_project test --wandb_group test --wandb_name test --wandb_entity zeyuanfe --use_ISAAC --headless True
python run_experiment.py --mode test --experiment_name quadruped_Ham-CA  --dt 0.02 --checkpoint_toload -1 --num_scenarios 1000000 --num_violations 10000 --control_type value --data_step run_robust_recovery --wandb_project test --wandb_group test --wandb_name test --wandb_entity zeyuanfe --use_ISAAC --headless True
python run_experiment.py --mode test --experiment_name quadruped_FVI --dt 0.02 --checkpoint_toload -1 --num_scenarios 1000000 --num_violations 10000 --control_type value --data_step run_robust_recovery --wandb_project test --wandb_group test --wandb_name test --wandb_entity zeyuanfe --use_ISAAC --headless True
python run_experiment.py --mode test --experiment_name quadruped_D-FVI --dt 0.02 --checkpoint_toload -1 --num_scenarios 1000000 --num_violations 10000 --control_type value --data_step run_robust_recovery --wandb_project test --wandb_group test --wandb_name test --wandb_entity zeyuanfe --use_ISAAC --headless True


